### ISSUE TITLE
Treasuries option in the ballot creation form needs to filter the options

### ISSUE THREAD

**Issue by poplexity** [telosnetwork/app-telos-net#43]
The getter for those options is here:

https://github.com/telosnetwork/app-telos-net/blob/7e36abb99491f291500dc8c180caf055b522902a/src/pages/trails/ballots/components/ballot-form.vue#L47

An account can only create ballots in treasuries which it is registered for, as seen in the contract code where it looks up the tables:

https://github.com/telosnetwork/telos-decide/blob/22e300dd50db6709dc0d5115894dbc611b09a690/contracts/decide/src/ballot.cpp#L23

So, that getter needs to also filter where the current account is a voter.  Likely can do a lookup on the voters table and only show the treasuries you find there, similar to how the actual contract does the table lookup.

**Comment by karynemayer** [comment]
Fixed by #54
