### ISSUE TITLE
Properly configure ballots for votestake/voteliquid

### ISSUE THREAD

**Issue by poplexity** [telosnetwork/app-telos-net#44]
When creating a ballot, we should never create a ballot where votestake and voteliquid are both false, because then there will never be any vote weights to count, and voting will always fail with the "must vote with a positive amount" error.

When creating a ballot, voteliquid is always set to false and votestake is always set based on the stakeable value from the treasury's settings: 

https://github.com/telosnetwork/telos-decide/blob/22e300dd50db6709dc0d5115894dbc611b09a690/contracts/decide/src/ballot.cpp#L51

So, if a treasury's token is not stakable, we always should toggle voteliquid to true... which is the case for the VOTE token, this is why those ballots we have created for testing will never get votes.  If a treasury's token is stakable, we should give the user an option in the form "Would you like to count liquid or staked or both"... but we cannot ever submit a ballot with both of those values set to false (which is what ballots for the VOTE token currently do).  Maybe a message would be good in any case... "This treasury is not stakeable so liquid tokens will be used" or "This treasury is stakable, would you like to count liquid or staked tokens, or both?"

The settings should be on the treasury row, which I think should be loaded into the store already.  So you can check the value of the stakeable property on the treasury row's settings to see how to handle this on the ballot form.

To toggle ballot settings, we need to call the togglebal action:

https://github.com/telosnetwork/telos-decide/blob/22e300dd50db6709dc0d5115894dbc611b09a690/contracts/decide/src/ballot.cpp#L100

To call that action, we need to add another action to the array of actions we create in the addBallot function here: 

https://github.com/telosnetwork/app-telos-net/blob/7e36abb99491f291500dc8c180caf055b522902a/src/store/trails/actions.js#L145

To know what values the ballot will have for each setting, see the code in ballot.cpp above... voteliquid is always starting as false, and votestake is based on the stakeable setting, so based on that logic, and what the user has selected, need to toggle one or both of those settings by adding 1 or 2 actions to the actions array in addBallot function.

**Comment by karynemayer** [comment]
Fixed by #54
