### ISSUE TITLE
Confirmation dialog for ballot fee

### ISSUE THREAD

**Issue by poplexity** [telosnetwork/app-telos-net#47]
# Description
Currently, when the user opens a ballot, there is no indication that there is a fee associated with opening it. Before the user gets an error message or they're surprised by their reduced balance, we want to show them they'll be paying the fee.

### The expected flow
1. User clicks new ballot
2. User fills out ballot
3. User clicks create
4. New dialog/modal confirms they accept the fee
5. We send the transactions for ballot creation

# Acceptance criteria
- Dialog/modal appears when user clicks the create button
- Dialog/modal shows the [fee that will be paid](https://explorer-test.telos.net/account/telos.decide?tab=contract)
- Dialog/modal shows `Cancel` and `Accept` options
- Dialog/modal shows that user doesn't have enough funds when they don't have enough funds

**Comment by karynemayer** [comment]
Fixed by #59
